### ISSUE TITLE
Start video from some moment in the middle

### ISSUE THREAD

**Issue by rudnitskih** [Ihor92/sports_app_landing#12]
![image](https://user-images.githubusercontent.com/8848858/56816964-36a40480-684d-11e9-914c-7561e7746258.png)

**Comment by Ihor92** [comment]
Видео начинаеться с 30 секунды. Для этого нужно нажать на play и начинаеться с 30. Почему по умолчанию стоит 0 я не знаю!

**Comment by rudnitskih** [comment]
Тебе не нужен аттрибут постер, укажи правильный тип а не `ogg`

![image](https://user-images.githubusercontent.com/8848858/56837912-de88f480-6884-11e9-96dc-5097361f0872.png)
